# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /pages operations"""

import json
import logging
import os
from typing import Dict, Any, Optional, List
from api.client import make_api_request
from tools.page_reads import confluence_get_page, confluence_search

# Configure logging - use LOG_LEVEL from environment or default to INFO
log_level = os.getenv("LOG_LEVEL", "INFO").upper()
numeric_level = getattr(logging, log_level, logging.INFO)
logging.basicConfig(level=numeric_level)
logger = logging.getLogger("mcp_tools")


async def get_pages(
  param_id: Optional[List[int]] = None,
  param_space_id: Optional[List[int]] = None,
  param_sort: Optional[str] = None,
  param_status: Optional[List[str]] = None,
  param_title: Optional[str] = None,
  param_body_format: Optional[str] = None,
  param_subtype: Optional[str] = None,
  param_cursor: Optional[str] = None,
  param_limit: Optional[int] = None
) -> Dict[str, Any]:
    """List bounded page metadata using CQL and classic OAuth scopes.

    Body reads must use confluence_get_page and all continuation chunks.
    Use confluence_search with a space key for space-scoped enumeration.
    """
    if param_space_id or param_subtype or (param_status and param_status != ["current"]):
        raise ValueError("Use confluence_search with supported CQL filters; numeric space IDs, subtype and non-current status are unsupported here")
    if param_body_format:
        if not param_id or len(param_id) != 1 or any((param_title, param_sort, param_cursor)):
            raise ValueError("Read a single page body with confluence_get_page and its continuation chunks")
        if param_body_format not in {"storage", "body.storage"}:
            raise ValueError("Only storage body reads are supported")
        return await confluence_get_page(str(param_id[0]))
    clauses = ["type=page"]
    if param_id:
        if any(type(page_id) is not int or page_id <= 0 for page_id in param_id):
            raise ValueError("Page IDs must be positive integers")
        clauses.append("id IN (" + ",".join(str(value) for value in param_id) + ")")
    if param_title:
        clauses.append("title=" + json.dumps(param_title))
    sort = param_sort or "-modified-date"
    order = {"-modified-date": "lastmodified DESC", "modified-date": "lastmodified ASC", "title": "title ASC", "-title": "title DESC"}.get(sort)
    if not order:
        raise ValueError("Supported sort values: modified-date, -modified-date, title, -title")
    return await confluence_search(" AND ".join(clauses) + " ORDER BY " + order, param_limit if param_limit is not None else 5, param_cursor)


async def create_page(
    title: str,
    space_key: str,
    body_value: str = "",
    body_representation: str = "storage",
    status: str = "current",
    parent_id: Optional[str] = None
) -> Dict[str, Any]:
    """
    Create page using Confluence Cloud REST API

    Args:
        title (str): The title of the page (required)
        space_key (str): The key of the space where the page will be created (required)
        body_value (str): The content of the page (optional, defaults to empty string)
        body_representation (str): The format of the body content (optional, defaults to "storage")
        status (str): The status of the page - "current" or "draft" (optional, defaults to "current")
        parent_id (Optional[str]): The ID of the parent page (optional)

    Returns:
        Dict[str, Any]: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug(f"Making POST request to /content with title: {title}, space_key: {space_key}")

    # Validate required parameters
    if not title or not title.strip():
        error_msg = "Title is required and cannot be empty"
        logger.error(error_msg)
        raise ValueError(error_msg)

    if not space_key or not space_key.strip():
        error_msg = "Space key is required and cannot be empty"
        logger.error(error_msg)
        raise ValueError(error_msg)

    # Create the page data using Confluence Cloud API format
    data = {
        "type": "page",
        "title": title.strip(),
        "space": {
            "key": space_key.strip()
        },
        "body": {
            body_representation: {
                "value": body_value,
                "representation": body_representation
            }
        }
    }

    # Add parent ID if provided
    if parent_id:
        data["ancestors"] = [{"id": parent_id}]

    logger.debug(f"Request data: {data}")

    success, response = await make_api_request(
        "/content",
        method="POST",
        data=data
    )

    if not success:
        error_details = response.get('error', 'Request failed')
        error_message = f"Failed to create page '{title}': {error_details}"

        # Check for specific error cases and provide better messages
        if 'already exists with the same TITLE' in str(response):
            error_message = f"Cannot create page '{title}': A page with this title already exists in the space. Please choose a different title."

        logger.error(error_message)
        # Raise an exception instead of returning an error dict
        # This ensures the MCP framework properly signals the error to the agent
        raise Exception(error_message)

    logger.info(f"Page created successfully: {response.get('title')} (ID: {response.get('id')})")
    return response
