
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /spaces operations"""

import logging
import os
from typing import Dict, Any, List, Optional
from api.client import make_api_request
from tools.page_reads import confluence_list_spaces

# Configure logging - use LOG_LEVEL from environment or default to INFO
log_level = os.getenv("LOG_LEVEL", "INFO").upper()
numeric_level = getattr(logging, log_level, logging.INFO)
logging.basicConfig(level=numeric_level)
logger = logging.getLogger("mcp_tools")


async def get_spaces(
  param_ids: Optional[List[int]] = None,
  param_keys: Optional[List[str]] = None,
  param_type: Optional[str] = None,
  param_status: Optional[str] = None,
  param_labels: Optional[List[str]] = None,
  param_favorited_by: Optional[str] = None,
  param_not_favorited_by: Optional[str] = None,
  param_sort: Optional[str] = None,
  param_description_format: Optional[str] = None,
  param_include_icon: Optional[bool] = None,
  param_cursor: Optional[str] = None,
  param_limit: Optional[int] = None
) -> Dict[str, Any]:
    """List bounded space metadata through classic-scope CQL.

    Filters apply to the current provider batch. Follow next_cursor even when
    filtering leaves an empty batch; complete refers to provider enumeration.
    Description/icon expansion and legacy sort/favorite/label filters fail
    explicitly rather than calling a retired endpoint or ignoring filters.
    """
    if any(value is not None for value in (param_labels, param_favorited_by, param_not_favorited_by, param_sort, param_description_format)) or param_include_icon:
        raise ValueError("Space description/icon, label, favorite and sort filters are unsupported by this bounded CQL reader")
    result = await confluence_list_spaces(param_limit if param_limit is not None else 5, param_cursor)
    spaces = result["results"]
    if param_ids:
        spaces = [space for space in spaces if str(space["id"]) in {str(value) for value in param_ids}]
    if param_keys:
        spaces = [space for space in spaces if space["key"] in param_keys]
    if param_type:
        spaces = [space for space in spaces if space["type"] == param_type]
    if param_status:
        if any(space["status"] is None for space in spaces):
            raise ValueError("Provider space metadata has no status; status filtering cannot be verified")
        spaces = [space for space in spaces if space["status"] == param_status]
    return {**result, "results": spaces}


async def create_space() -> Dict[str, Any]:
    """
    Create space

    OpenAPI Description:
        Creates a Space as specified in the payload.

**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
Permission to create spaces.

    Args:


    Returns:
        Dict[str, Any]: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making POST request to /spaces")

    params = {}
    data = {}




    success, response = await make_api_request(
        "/space",
        method="POST",
        params=params,
        data=data
    )

    if not success:
        error_details = response.get('error', 'Request failed')
        error_message = f"Failed to create space: {error_details}"
        logger.error(error_message)
        raise Exception(error_message)
    return response
